export const cuisineList: Record<"veg" | "non-veg" | "mixed", string[]> = {
  veg: [
    "South Indian",
    "North Indian",
    "Udupi",
    "Gujarati",
    "Rajasthani",
    "Maharashtrian",
    "Punjabi",
    "Jain",
    "Vegan",
    "Vegetarian",
    "Street Food",
    "Chaat",
    "Snacks & Fast Food",
    "Bakery & Desserts",
    "Continental Veg",
    "Italian Veg",
    "Chinese Veg",
    "Healthy & Salads",
    "GSB",
    "Satvik Food",
  ],
  "non-veg": [
    "North Indian Non-Veg",
    "South Indian Non-Veg",
    "Andhra",
    "Hyderabadi",
    "Mughlai",
    "Kebab & Grills",
    "Seafood",
    "Coastal",
    "Biryani",
    "Chinese Non-Veg",
    "Thai",
    "Middle Eastern",
    "Continental Non-Veg",
    "Italian Non-Veg",
  ],
  mixed: [
    "South Indian",
    "North Indian",
    "Udupi",
    "Andhra",
    "Hyderabadi",
    "Mughlai",
    "Kebab & Grills",
    "Seafood",
    "Coastal",
    "Biryani",
    "Chinese Non-Veg",
    "Thai",
    "Middle Eastern",
    "Continental Non-Veg",
    "Italian Non-Veg",
    "Korean",
    "Japanese",
    "Taiwanese",
    "Vietnamese",
  ],
}
